name: CI/CD Workflow

on:
  push:
    branches-ignore:
      - main 

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.DAS_TOKEN }}
          commit-message: "Automatic pull request"
          committer: "GitHub Actions <actions@github.com>"
          author: "GitHub Actions <actions@github.com>"
          branch: main
          title: "Auto PR from ${{ github.ref }}"
          body: "This is an automatically created pull request from ${{ github.ref }}."
          reviewers: |
            Sebastchan8
            PsychoticProgrammer
          assignees: |
            Sebastchan8
            PsychoticProgrammer
          labels: |
            auto-pr

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: github.event.pull_request.merged == true

    steps:
      - name: Merge Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DAS_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;

            await github.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              commit_title: Merge pull request #${prNumber},
              commit_message: 'Auto-merge pull request',
              merge_method: 'squash'
            });

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: merge-pull-request

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Install StyleLint
        run: npm install -g stylelint stylelint-config-standard

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run HTMLHint
        run: htmlhint "*/.html"

      - name: Run StyleLint
        run: stylelint "*/.css"

      - name: Run ESLint
        run: eslint "*/.js"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DAS_TOKEN }}
          publish_dir: ./  # Publica desde la raíz del proyecto