name: CI/CD Workflow

on:
  push:
    branches:
      - main 

jobs:
  updateAuthor:
    runs-on: ubuntu-latest

    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update Author Information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "develop"
          base: main
          title: "demo for auto pr from ${{ github.ref }}"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
  #         commit-message: "Automatic pull request"
  #         body: "This is an automatically created pull request from ${{ github.ref }}."
  #         reviewers: |
  #           Sebastchan8
  #           PsychoticProgrammer
  #         assignees: |
  #           Sebastchan8
  #           PsychoticProgrammer
  #         labels: |
  #           auto-pr

  # merge-pull-request:
  #   runs-on: ubuntu-latest
  #   needs: create-pull-request
  #   if: github.event.pull_request.merged == true

  #   steps:
  #     - name: Merge Pull Request
  #       uses: actions/github-script@v6
  #       with:
  #         github-token: ${{ secrets.DAS_TOKEN }}
  #         script: |
  #           const { owner, repo } = context.repo;
  #           const prNumber = context.payload.pull_request.number;

  #           await github.pulls.merge({
  #             owner,
  #             repo,
  #             pull_number: prNumber,
  #             commit_title: Merge pull request #${prNumber},
  #             commit_message: 'Auto-merge pull request',
  #             merge_method: 'squash'
  #           });

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: merge-pull-request

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Install HTMLHint
  #       run: npm install -g htmlhint

  #     - name: Install StyleLint
  #       run: npm install -g stylelint stylelint-config-standard

  #     - name: Install ESLint
  #       run: npm install -g eslint

  #     - name: Run HTMLHint
  #       run: htmlhint "*/.html"

  #     - name: Run StyleLint
  #       run: stylelint "*/.css"

  #     - name: Run ESLint
  #       run: eslint "*/.js"

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.DAS_TOKEN }}
  #         publish_dir: ./  # Publica desde la raíz del proyecto