name: Create Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated pull request from ${{ github.actor }}
          branch: auto-pr-${{ github.head_ref }}
          title: 'Automated PR: ${{ github.head_ref }}'
          body: 'This pull request has been created automatically by the push event on branch ${{ github.head_ref }}.'

